Feat/about us
PrayTeam/scriptured-prayer pull request #104
Opened 2024-03-21 20:02 UTC by JudahRininger

I added a carousel to the about page with cards displaying the pray team

## Description

I added a swiper slider with placeholder names, descriptions, and images to the about page and left the placeholder contact information on the top of the page.

## Reason

the purpose of this change is to provide a place to credit the developers

## How this has been tested

I tested scalability with the device toolbar in google chrome.

## Types of changes

- [x] New feature (adds functionality)
- [ ] Bug fix (fixes an issue)
- [ ] Breaking changes (causes defects to existing pieces)

## Screenshots
<img width="1440" alt="Screenshot 2024-03-21 at 3 01 05 PM" src="https://github.com/PrayTeam/scriptured-prayer/assets/70775371/9df21c18-b4c9-4a3e-a144-3b791a1ffcb4">

## Checklist:

- [ ] I have read and complied with the **CONTRIBUTING** document
- [ ] The changes I've made follow the existing code style and formatting requirements
- [ ] My changes require updates to the documentation, which I have modified accordingly

2024-04-09 00:55 UTC, asherlloyd requested changes

2024-04-09 00:55 UTC, asherlloyd commented on scriptured-prayer-components/src/assets/images/No_image_available.svg
Verify the source of this vector image

2024-04-09 00:55 UTC, asherlloyd commented on scriptured-prayer-components/src/components/TeamMemberCard.tsx
> +interface Props {
Rename to `TeamMemberCardProps` for consistency as compared with other components.

2024-04-09 00:56 UTC, asherlloyd commented on scriptured-prayer-components/src/views/About.tsx
The background image is tiling; it should instead fully cover the background.

![image](https://github.com/PrayTeam/scriptured-prayer/assets/23032713/2ee9393a-d439-465c-88da-19a439d3e193)

2024-04-09 17:08 UTC, kenancasey commented on scriptured-prayer-components/src/views/About.tsx
> +              <div className="my-2">hello@scripturedprayer.com</div>
I agree, especially about the phone number. My gut is that we should make a gmail address for the site (and forward it to @follindown?) as one point of contact.

2024-04-09 19:59 UTC, JudahRininger commented on scriptured-prayer-components/src/assets/images/No_image_available.svg
I got this image from Google icons, which is free to use and doesn't require any attribution to them.

2024-04-09 19:59 UTC, JudahRininger commented on scriptured-prayer-components/src/assets/images/No_image_available_white.svg
I got this image from Google icons, which is free to use and doesn't require any attribution to them.

2024-04-23 19:03 UTC, kenancasey requested changes
Please address these comments.

2024-04-23 19:03 UTC, kenancasey commented on scriptured-prayer-components/src/components/TeamMemberCarousel.tsx
> +      description: "Back-End Developer",
Spelling: `Backend` not `Back-End`

2024-04-23 19:03 UTC, kenancasey commented on scriptured-prayer-components/src/views/About.tsx
> +                <div className="my-2">(123) 456-7890</div>
Are we even going to have a phone? I think we should just remove this.

2024-04-27 13:13 UTC, LTsoccer approved these changes
Works locally. Code looks decent. Suggested changes to some wording issues.

2024-04-27 13:13 UTC, LTsoccer commented on scriptured-prayer-components/src/views/About.tsx
> +            Meet the Pray Team
Maybe just say Meet the Team.

2024-04-27 13:13 UTC, LTsoccer commented on scriptured-prayer-components/src/components/TeamMemberCarousel.tsx
> +      position: "Freed Hardeman Alumn",
I would swap position and description here to match the others more

2024-05-05 04:00 UTC, LouviersJ approved these changes
I agree with Lauren just saying "Meet the team" would be more cogent. This is some good code!

2024-05-05 04:09 UTC, LouviersJ commented
Pagination kinda stinks but that should be resolved with my pull request

2024-06-07 02:22 UTC, closed without merging