Feat/home faq
PrayTeam/scriptured-prayer pull request #112
Opened 2024-04-12 20:09 UTC by sflowers51

implemented home faq section, .gitignore updated
## Description

implemented home faq section of the home page as well as made changes to .gitignore as requested by Kenan

## Reason

Home faq section needs to be implemented and conflicts with previous pull requests require changes to .gitignore

## How this has been tested

Tested window at three different widths - full screen, medium, mobile width- to ensure the faq section responds appropriately

## Types of changes

- [x] New feature (adds functionality)
- [x] Bug fix (fixes an issue)
- [ ] Breaking changes (causes defects to existing pieces)

## Screenshots

## Checklist:

- [x] I have read and complied with the **CONTRIBUTING** document
- [x] The changes I've made follow the existing code style and formatting requirements
- [ ] My changes require updates to the documentation, which I have modified accordingly

2024-05-02 20:28 UTC, SeanJaniec commented
First, Great Job Sam. However, for me, it's too crowded. I don't like how the first faq is already open. Additionally, I believe there are too many FAQs on display, can hide some them and give an option to "display more FAQs." More vertical margin between the FAQs would help with the crowded look. Again, I like the overall look and simplicity, but I think some small adjustments would allow this component to better fit the aesthetic of scriptured prayer.

2024-05-02 20:29 UTC, SeanJaniec approved these changes

2024-05-02 22:00 UTC, jaydondulgar requested changes

2024-05-03 02:44 UTC, jaydondulgar commented on scriptured-prayer-components/src/components/Faq.tsx
> +import * as Accordion from "@radix-ui/react-accordion";
Sean ran into the same problem but found a work around. If you run: npm install @radix-ui/react-menu in the terminal, then you can locally run the website.

2024-06-07 05:21 UTC, asherlloyd approved these changes

2024-06-07 05:23 UTC, merged