feat: add footer component
PrayTeam/scriptured-prayer pull request #89
Opened 2024-03-11 22:35 UTC by savannah-martin

Add Footer Component

## Description
Created footer component and added footer component onto info, home, and about views.

## Reason
#77 

## How this has been tested
Tested in dev environment on two different machines

## Types of changes

- [x] New feature (adds functionality)
- [ ] Bug fix (fixes an issue)
- [ ] Breaking changes (causes defects to existing pieces)

## Screenshots

## Checklist:

- [x] I have read and complied with the **CONTRIBUTING** document
- [x] The changes I've made follow the existing code style and formatting requirements
- [ ] My changes require updates to the documentation, which I have modified accordingly

2024-03-12 13:14 UTC, asherlloyd commented on scriptured-prayer-components/src/views/Info.tsx
> +      <Footer color="lichen"></Footer>
I'm hesitant to use the same background color for the homepage and this footer. Google Lighthouse, for example, reports insufficient contrast for accessibility standards:

![image](https://github.com/PrayTeam/scriptured-prayer/assets/23032713/b3c6af61-9188-4deb-b13f-7237995a0e13)

![image](https://github.com/PrayTeam/scriptured-prayer/assets/23032713/c0a276e4-2d71-4019-9f98-49873b98eddb)

Change it to something darker for a higher contrast.

2024-03-12 13:44 UTC, asherlloyd commented on scriptured-prayer-components/src/components/Footer.tsx
> +  color: keyof typeof theme.colors;
Since it seems like `keyof typeof theme.colors;` is being reused in several places (I count 4 at the time of writing) - consider adding a type definition for it somewhere that would allow its reuse and increase clarity:

`type ThemeColor = keyof typeof theme.colors;`

2024-03-12 13:46 UTC, asherlloyd commented on scriptured-prayer-components/src/components/Footer.tsx
> +        <div className="flex flex-col space-y-4 items-center ">
Remove trailing space

2024-03-12 13:46 UTC, asherlloyd commented on scriptured-prayer-components/src/components/Footer.tsx
> +        <div className="flex flex-col space-y-4 items-center ">
Remove trailing space

2024-03-12 13:52 UTC, asherlloyd commented on scriptured-prayer-components/src/components/Footer.tsx
> +        <div className="flex flex-col space-y-4 items-center ">
Having the `items-center` class causes the child elements to have odd alignment:

![image](https://github.com/PrayTeam/scriptured-prayer/assets/23032713/a7dbee26-529d-49b8-872b-7716d32692a6)

As the screenshot indicates, the links should sit flush with their headings for greater readability.

2024-03-12 13:59 UTC, asherlloyd commented on scriptured-prayer-components/src/components/Footer.tsx
The mobile styles for the footer are frankly all over the place. It looks very disjointed:

![image](https://github.com/PrayTeam/scriptured-prayer/assets/23032713/1a757e8b-2a84-4003-b272-9fe36e46c5ea)

I think the dual-column layout for the link sections with headings is alright; for the copyright text and links it should be left aligned and not word-wrapped in such an odd fashion. Here is a good example that approximates what you want to do:

![image](https://github.com/PrayTeam/scriptured-prayer/assets/23032713/98d5ef6c-519d-4d5e-9590-b417f73ebd37)

2024-03-13 20:49 UTC, savannah-martin commented
We've tried to change what you requested. Would you review this branch again and clarify anything we misunderstood? Thank you! @asherlloyd

2024-03-14 13:49 UTC, asherlloyd requested changes

2024-03-14 13:49 UTC, asherlloyd commented on scriptured-prayer-components/src/views/About.tsx
> +      <Footer color="snowgrass" text="black"></Footer>
```suggestion
      <Footer color="snowgrass" text="black" />
```

2024-03-14 13:49 UTC, asherlloyd commented on scriptured-prayer-components/src/components/Footer.tsx
Decrease left and right padding on smaller resolutions; it's causing the "Scriptured Prayer" title to wrap:

![image](https://github.com/PrayTeam/scriptured-prayer/assets/23032713/a674c3fb-1b6f-4526-9d1f-5616b7694159)

2024-03-14 13:49 UTC, asherlloyd commented on scriptured-prayer-components/src/views/Home.tsx
> +      <Container className="grow flex w-4/5">
```suggestion
      <Container className="grow flex">
```

2024-03-14 13:49 UTC, asherlloyd commented on scriptured-prayer-components/src/views/Home.tsx
> +        <div className="flex flex-col w-full px-8">
```suggestion
        <div className="flex flex-col w-full">
```

2024-03-14 13:49 UTC, asherlloyd commented on scriptured-prayer-components/src/views/About.tsx
Fix footer not sitting flush with the bottom of the page on the About screen:

![image](https://github.com/PrayTeam/scriptured-prayer/assets/23032713/c77ecb4c-dc15-40a1-a16e-0493b324156e)

2024-03-14 13:49 UTC, asherlloyd commented on scriptured-prayer-components/yarn.lock
Still not resolved

2024-03-14 13:49 UTC, asherlloyd commented on scriptured-prayer-components/src/components/Footer.tsx
> +    </footer>
```suggestion
    <footer
      className="dark:bg-gray-800 dark:text-gray-100 text-white"
      style={{ backgroundColor: theme.colors[color], color: text }}
    >
      <div className="px-6 py-10 max-w-screen-xl mx-auto">
        <div className="grid grid-cols-2 mx-auto gap-x-3 gap-y-8 sm:grid-cols-3 md:grid-cols-4 sm:justify-items-center md:justify-items-center">
          <FooterColumn>
            <h1 className="text-2xl font-bold">Scriptured Prayer</h1>
            <h2 className="font-medium">Logo placeholder</h2>
          </FooterColumn>
          <FooterColumn>
            <h2 className="font-semibold text-base">Useful Links</h2>
            <FooterLinks>
              {/* TODO: fix these links to work with Spanish */}
              <FooterLink link="/en/about">About Us</FooterLink>
              <FooterLink link="/en/info">Info</FooterLink>
              <FooterLink link="/en/FAQ">FAQ</FooterLink>
            </FooterLinks>
          </FooterColumn>

          <FooterColumn>
            <h2 className="font-semibold text-base">Contact Us</h2>
            <FooterLinks>
              <FooterLink link="https://github.com/PrayTeam">GitHub</FooterLink>
              <FooterLink link="#">Discord</FooterLink>
              <FooterLink link="#">Facebook</FooterLink>
              <FooterLink link="#">Email</FooterLink>
            </FooterLinks>
          </FooterColumn>

          <FooterColumn>
            <h2 className="font-semibold text-base">Support</h2>
            <FooterLinks>
              <Button
                className="border border-stone bg-leaf hover:scale-105 transition duration-150"
                onClick={() => navigate("/donate")}
              >
                Donate
              </Button>
            </FooterLinks>
          </FooterColumn>
        </div>
        <div className="flex items-center justify-center mt-12 text-sm flex-row space-x-8">
          <span className="dark:text-gray-400">
            © Copyright 2024. All Rights Reserved.
          </span>
          <span>
            <FooterLink link="/en/privacy" className="text-gray hover:underline">
              Privacy Policy
            </FooterLink>
          </span>
        </div>
      </div>
    </footer>
```

2024-03-14 20:19 UTC, asherlloyd requested changes

2024-03-14 20:19 UTC, asherlloyd commented on scriptured-prayer-components/src/views/About.tsx
Stretched image on the about page:

![image](https://github.com/PrayTeam/scriptured-prayer/assets/23032713/6c5dc56b-cd50-4f1e-9ca5-96b27237d98b)

2024-03-16 18:52 UTC, LouviersJ commented on scriptured-prayer-components/src/views/Home.tsx
I don't see that when I emulate a mobile device from windows?

2024-03-16 21:31 UTC, asherlloyd requested changes

2024-03-16 21:31 UTC, asherlloyd commented on scriptured-prayer-components/src/views/About.tsx
> +        />
```suggestion
      <div className="lg:flex px-6 py-8 lg:py-16 lg:space-x-12 lg:items-center max-w-screen-xl mx-auto grow">
        <div className="max-w-[700px] mb-8">
          <img src={dryGrass} />
        </div>
```

2024-03-16 21:31 UTC, asherlloyd commented on scriptured-prayer-components/src/views/Home.tsx
> +      <Container className="grow flex">
```suggestion
      <Container className="grow flex w-full">
```

2024-03-16 21:31 UTC, asherlloyd commented on scriptured-prayer-components/src/views/Home.tsx
> +            <div className="flex flex-wrap md:flex-wrap overflow-x-auto gap-x-4 -mx-6 md:mx-0 px-6 md:px-0">
```suggestion
            <div className="flex flex-nowrap md:flex-wrap overflow-x-auto gap-x-4 -mx-6 md:mx-0 px-6 md:px-0">
```

2024-03-17 02:34 UTC, asherlloyd approved these changes

2024-03-17 02:34 UTC, merged